temporal:
  url: resilmesh-sop-wo-temporal:7233
  namespace: default
  csa_task_queue: csa

isim:
  url: "http://resilmesh-sap-isim:8000"

neo4j:
  bolt: "bolt://neo4j:7687"
  user: "neo4j"
  password: "supertestovaciheslo"
